/**
 * Batch test scenario generation
 *
 * Generates multiple complete test sequences in a single LLM call
 * to minimize API costs and latency.
 *
 * Supports multiple providers via Vercel AI SDK:
 * - anthropic: Claude models via API key
 * - openai: GPT models via API key
 * - claude-code: Use Claude Code CLI for subscription-based pricing
 */

import { generateText } from 'ai'
import { createAnthropic } from '@ai-sdk/anthropic'
import { createOpenAI } from '@ai-sdk/openai'
import { spawn } from 'child_process'
import type { SystemContext } from './introspect.js'
import { formatContextForLLM } from './introspect.js'

/**
 * A complete test scenario generated by the LLM
 */
export interface TestScenario {
  /** Human-readable name for the scenario */
  name: string
  /** What this scenario is testing */
  description: string
  /** The sequence of actions to execute */
  actions: string[]
  /** Why the LLM chose this sequence */
  reasoning: string
  /** Expected outcome (pass/which invariant might fail) */
  expectation: 'pass' | { failsInvariant: string }
}

/**
 * Result of batch generation
 */
export interface BatchGenerationResult {
  scenarios: TestScenario[]
  tokensUsed: number
  model: string
}

/**
 * Options for batch generation
 */
export interface BatchGenerationOptions {
  /** Number of scenarios to generate */
  count: number
  /** Maximum actions per scenario */
  maxActionsPerScenario: number
  /** LLM model to use */
  model: string
  /** Temperature (0 = deterministic) */
  temperature: number
  /** API key (reads from env if not provided) */
  apiKey?: string
  /** Provider */
  provider: 'openai' | 'anthropic' | 'claude-code'
}

const DEFAULT_OPTIONS: BatchGenerationOptions = {
  count: 10,
  maxActionsPerScenario: 20,
  model: 'claude-sonnet',
  temperature: 0,
  provider: 'anthropic',
}

/**
 * Generate test scenarios using LLM
 *
 * Makes a single API call to generate multiple complete test sequences.
 */
export async function generateTestScenarios(
  context: SystemContext,
  options: Partial<BatchGenerationOptions> = {}
): Promise<BatchGenerationResult> {
  const opts = { ...DEFAULT_OPTIONS, ...options }

  const prompt = buildBatchPrompt(context, opts)

  // For now, return mock scenarios
  // Real implementation would call LLM API
  if (process.env.VITESTX_AI_MOCK !== 'false') {
    return generateMockScenarios(context, opts)
  }

  // Real LLM call would go here
  // Using Anthropic API or OpenAI API based on provider
  const response = await callLLM(prompt, opts)

  return {
    scenarios: parseScenarioResponse(response, context.actions.map((a) => a.name)),
    tokensUsed: response.tokensUsed,
    model: opts.model,
  }
}

/**
 * Build the prompt for batch scenario generation
 */
function buildBatchPrompt(
  context: SystemContext,
  options: BatchGenerationOptions
): string {
  const systemContext = formatContextForLLM(context)

  return `You are a test scenario generator. Your goal is to find edge cases and potential bugs.

${systemContext}

Generate ${options.count} test scenarios. Each scenario should:
1. Have a clear purpose (what it's testing)
2. Be a sequence of ${options.maxActionsPerScenario} or fewer actions
3. Focus on edge cases, boundary conditions, and potential invariant violations
4. Include reasoning for why this sequence might be interesting

${context.focus ? `\nFocus areas: ${context.focus.join(', ')}` : ''}

Respond with JSON array:
\`\`\`json
[
  {
    "name": "scenario name",
    "description": "what this tests",
    "actions": ["action1", "action2", ...],
    "reasoning": "why this might find bugs",
    "expectation": "pass" or {"failsInvariant": "invariantName"}
  }
]
\`\`\`

Be creative. Try to break the system. Think about:
- Boundary conditions (empty, full, zero, negative)
- Rapid sequences of the same action
- Unusual orderings
- State transitions that might be missed

Generate diverse scenarios that cover different aspects of the system.`
}

/**
 * Generate mock scenarios for testing without LLM
 */
function generateMockScenarios(
  context: SystemContext,
  options: BatchGenerationOptions
): BatchGenerationResult {
  const actions = context.actions.map((a) => a.name)
  const scenarios: TestScenario[] = []

  // Generate diverse mock scenarios
  const patterns = [
    {
      name: 'single action repeated',
      gen: () => Array(options.maxActionsPerScenario).fill(actions[0]),
    },
    {
      name: 'all actions once',
      gen: () => actions.slice(0, options.maxActionsPerScenario),
    },
    {
      name: 'alternating first two',
      gen: () =>
        Array(options.maxActionsPerScenario)
          .fill(0)
          .map((_, i) => actions[i % 2] || actions[0]),
    },
    {
      name: 'reverse order',
      gen: () => [...actions].reverse().slice(0, options.maxActionsPerScenario),
    },
    {
      name: 'random-ish mix',
      gen: () =>
        Array(options.maxActionsPerScenario)
          .fill(0)
          .map((_, i) => actions[i % actions.length]),
    },
  ]

  for (let i = 0; i < Math.min(options.count, patterns.length); i++) {
    const pattern = patterns[i]
    scenarios.push({
      name: `mock-scenario-${i + 1}`,
      description: `Mock: ${pattern.name}`,
      actions: pattern.gen(),
      reasoning: `Generated pattern: ${pattern.name}`,
      expectation: 'pass',
    })
  }

  // Fill remaining with variations
  while (scenarios.length < options.count) {
    const base = patterns[scenarios.length % patterns.length]
    scenarios.push({
      name: `mock-scenario-${scenarios.length + 1}`,
      description: `Mock variation: ${base.name}`,
      actions: base.gen().slice(0, Math.floor(Math.random() * options.maxActionsPerScenario) + 1),
      reasoning: 'Mock variation',
      expectation: 'pass',
    })
  }

  return {
    scenarios,
    tokensUsed: 0,
    model: 'mock',
  }
}

/**
 * Map user-friendly model names to provider-specific model IDs
 */
function resolveModel(model: string, provider: string): string {
  const anthropicModels: Record<string, string> = {
    'claude-sonnet': 'claude-sonnet-4-20250514',
    'claude-opus': 'claude-opus-4-20250514',
    'claude-haiku': 'claude-haiku-4-20250514',
  }

  const openaiModels: Record<string, string> = {
    'gpt-4': 'gpt-4-turbo',
    'gpt-4o': 'gpt-4o',
    'gpt-3.5': 'gpt-3.5-turbo',
  }

  if (provider === 'anthropic' || provider === 'claude-code') {
    return anthropicModels[model] ?? model
  }
  if (provider === 'openai') {
    return openaiModels[model] ?? model
  }
  return model
}

/**
 * Call LLM using Vercel AI SDK (Anthropic provider)
 */
async function callWithAnthropic(
  prompt: string,
  options: BatchGenerationOptions
): Promise<{ content: string; tokensUsed: number }> {
  const apiKey = options.apiKey ?? process.env.ANTHROPIC_API_KEY

  if (!apiKey) {
    throw new Error(
      'No API key found for Anthropic. Set ANTHROPIC_API_KEY env var or pass apiKey option.'
    )
  }

  const anthropic = createAnthropic({ apiKey })
  const modelId = resolveModel(options.model, 'anthropic')

  const result = await generateText({
    model: anthropic(modelId),
    prompt,
    maxTokens: 4096,
    temperature: options.temperature,
  })

  const tokensUsed = (result.usage?.promptTokens ?? 0) + (result.usage?.completionTokens ?? 0)
  return { content: result.text, tokensUsed }
}

/**
 * Call LLM using Vercel AI SDK (OpenAI provider)
 */
async function callWithOpenAI(
  prompt: string,
  options: BatchGenerationOptions
): Promise<{ content: string; tokensUsed: number }> {
  const apiKey = options.apiKey ?? process.env.OPENAI_API_KEY

  if (!apiKey) {
    throw new Error(
      'No API key found for OpenAI. Set OPENAI_API_KEY env var or pass apiKey option.'
    )
  }

  const openai = createOpenAI({ apiKey })
  const modelId = resolveModel(options.model, 'openai')

  const result = await generateText({
    model: openai(modelId),
    prompt,
    maxTokens: 4096,
    temperature: options.temperature,
  })

  const tokensUsed = (result.usage?.promptTokens ?? 0) + (result.usage?.completionTokens ?? 0)
  return { content: result.text, tokensUsed }
}

/**
 * Call Claude Code CLI for subscription-based pricing
 *
 * This uses your existing Claude Code subscription instead of API credits.
 * Runs `claude --print` with the prompt and captures the output.
 */
async function callWithClaudeCode(
  prompt: string,
  _options: BatchGenerationOptions
): Promise<{ content: string; tokensUsed: number }> {
  return new Promise((resolve, reject) => {
    // Use claude CLI with --print flag for non-interactive output
    const proc = spawn('claude', ['--print', '-p', prompt], {
      stdio: ['pipe', 'pipe', 'pipe'],
      env: { ...process.env },
    })

    let stdout = ''
    let stderr = ''

    proc.stdout.on('data', (data) => {
      stdout += data.toString()
    })

    proc.stderr.on('data', (data) => {
      stderr += data.toString()
    })

    proc.on('close', (code) => {
      if (code !== 0) {
        reject(
          new Error(
            `Claude Code CLI exited with code ${code}: ${stderr || 'No error output'}`
          )
        )
        return
      }

      // Claude Code doesn't report token usage
      resolve({ content: stdout.trim(), tokensUsed: 0 })
    })

    proc.on('error', (err) => {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
        reject(
          new Error(
            'Claude Code CLI not found. Install it or use anthropic/openai provider instead.'
          )
        )
      } else {
        reject(err)
      }
    })
  })
}

/**
 * Call LLM API based on provider
 */
async function callLLM(
  prompt: string,
  options: BatchGenerationOptions
): Promise<{ content: string; tokensUsed: number }> {
  switch (options.provider) {
    case 'anthropic':
      return callWithAnthropic(prompt, options)

    case 'openai':
      return callWithOpenAI(prompt, options)

    case 'claude-code':
      return callWithClaudeCode(prompt, options)

    default:
      throw new Error(`Unknown provider: ${options.provider}`)
  }
}

/**
 * Parse LLM response into scenarios
 */
function parseScenarioResponse(
  response: { content: string; tokensUsed: number },
  validActions: string[]
): TestScenario[] {
  try {
    // Extract JSON from markdown code block if present
    let json = response.content
    const match = json.match(/```json\s*([\s\S]*?)\s*```/)
    if (match) {
      json = match[1]
    }

    const parsed = JSON.parse(json) as TestScenario[]

    // Validate and filter to valid actions
    return parsed.map((scenario) => ({
      ...scenario,
      actions: scenario.actions.filter((a) => validActions.includes(a)),
    }))
  } catch {
    console.error('Failed to parse LLM response, returning empty scenarios')
    return []
  }
}
