/**
 * Save AI-discovered tests as regression tests
 */

import type { AiStep } from './harness.js'

export interface SaveOptions {
  outputDir: string
  specPath: string
}

/**
 * Generate test code from AI exploration steps
 */
export function generateTestCode(
  steps: AiStep[],
  specPath: string,
  testName: string
): string {
  const actions = steps.map((s) => s.action)
  const importPath = specPath.replace(/\.spec\.ts$/, '.spec')

  return `/**
 * Generated by vitestx AI mode
 * Date: ${new Date().toISOString()}
 * Original spec: ${specPath}
 */

import { test, expect } from 'vitest'
import { surface } from '${importPath}'

test('${testName}', () => {
  const instance = surface.create()

${actions.map((action, i) => {
    const reasoning = steps[i]?.reasoning ? `: ${steps[i].reasoning}` : ''
    return `  // Step ${i + 1}${reasoning}
  surface.sendAction(instance, '${action}')`
  }).join('\n\n')}

  const state = surface.getState(instance)
  // Add assertions based on final state
  expect(state).toBeDefined()
})
`
}

/**
 * Save generated test to file
 *
 * TODO: Implement file writing with proper path handling
 */
export async function saveGeneratedTest(
  steps: AiStep[],
  specPath: string,
  testName: string,
  options: SaveOptions
): Promise<string> {
  const code = generateTestCode(steps, specPath, testName)
  const fileName = `${testName.replace(/\s+/g, '-').toLowerCase()}.test.ts`
  const outputPath = `${options.outputDir}/${fileName}`

  // TODO: Actually write file
  console.log(`Would save to: ${outputPath}`)
  console.log(code)

  return outputPath
}
